### ISSUE TITLE
Add support for terraform 0.12

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/terraform-provider-cf#126]
See https://www.terraform.io/upgrade-guides/0-12.html#upgrading-terraform-providers

> To upgrade a provider to use the new RPC plugin protocol in 0.12 and remain backwards compatible with previous releases, providers will need to update their Terraform dependencies to a 0.12 release. The changes to the helper packages are being designed so that updating the packages will allow the provider to work with the new plugin protocol, while remaining compatible with previous Terraform releases.

**Comment by janosbinder** [comment]
* [ ] adopt the provider to support the enhancements to HCL (see https://www.hashicorp.com/blog/)
* [ ] define the necessary migration steps in the *.tf files

**Comment by gberche-orange** [comment]
Reading from https://www.terraform.io/upgrade-guides/0-12.html#upgrading-terraform-providers it seems that 0.9.9 will be useable from tf 0.11 and 0.12. No rush then to get this in 1.0. Therefore, we don't include it into the 1.0 milestone

> To avoid the need to atomically upgrade both Terraform Core and the providers all at once, new provider versions will be released that are compatible with both v0.12 and prior versions. Users will need to upgrade to the new v0.12-compatible provider releases before upgrading Terraform Core, but can use these newer provider releases with prior Terraform versions to transition gradually and reduce risk.

**Comment by ArthurHlt** [comment]
This has been done in #203 

* ~[ ] test the current terraform-provider-cf binaries can be used with terraform 0.12 binary~ obviously it wasn't the case.
For details:
- `schema.Resource` type change its behaviour, you can't update value during an update phase. This is probably due that terraform handle resource inside the resource. Setting crud function inside with an update modification should do the old behaviour (I didn't tried).
- Import mark that we were using (cause of me) for changing resource behaviour when found was not working because changing `conninfo` during import phase is not passed to read phase. The fixed was clearly make the reading ourself with marker.

* [x] update terraform-provider-cf to be compatible with 0.12
   * [x] use terraform 0.12 as a dependency **Note**: this is enabled by using go modules which makes things easier
   * [x] add support for the new RPC protocol
   * [x] adopt the provider to support the enhancements to HCL (see https://www.hashicorp.com/blog/)
   * [ ] define the necessary migration steps in the *.tf files if any (i.e. fix acceptance tests to be be green) => terraform help a lot on this, my concern is migrating state with breaking changes in #203

**Comment by ArthurHlt** [comment]
We will probably need a guide and also make a version `11.14` of our provider which include PR #203 because terraform recommend to users to update first on this version, fix the state and go to `11.12` and do the same. We also make breaking changes on #203 which need to be clearly documented.

Could you take this work @gberche-orange ?

**Comment by gberche-orange** [comment]
Thanks @ArthurHlt. I tried to rephrase your comment https://github.com/cloudfoundry-community/terraform-provider-cf/issues/126#issuecomment-496028280 below. Please correct me if I got it wrong.

----

We need make an intermediate a version of our provider (likely 1.0.0) with PR #203 and built against [terraform 0.11.14](https://github.com/hashicorp/terraform/releases/tag/v0.11.14) before we release a 1.1.0 of our provider built against terraform [0.12.0](https://github.com/hashicorp/terraform/releases/tag/v0.12.0) as recommended by hashicorp.

The upgrade path for users would then be:

1.  upgrade to terraform 0.11
2.  upgrade terraform-provider-cf from 0.x to 1.0.0 following a migration guide.
3.  apply the terraform 0.12 [upgrade procedure](https://www.terraform.io/upgrade-guides/0-12.html), likely including executing `terraform 0.12checklist` checklist released in [tf v0.11.14](https://github.com/hashicorp/terraform/releases/tag/v0.11.14)
4.  upgrade terraform-provider-cf from 1.0.0 to 1.1.0

----

Yes, I'll contribute the terraform-provider-cf 1.0 migration guide.

**Comment by ArthurHlt** [comment]
Looks good to me, thanks @gberche-orange

**Comment by ArthurHlt** [comment]
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.
