### ISSUE TITLE
Release convention

### ISSUE THREAD

**Issue by till** [cloudfoundry-community/terraform-provider-cf#204]
It's a bit odd how the (old) provider was renamed, then it was (I think) swapped out with another repo and then renamed again? I spent an hour trying to figure out which provider I can use, because your changelogs of minor releases contain the word "BC break" and that worries me.

It wouldn't hurt if you released a 1.0 and then a 2.0 to make it more obvious. :-)

**Comment by ArthurHlt** [comment]
Thanks for your feedbacks @till . We had 2 providers and try to only focus on one (this one). We renamed it because we want to sweep the orange one and also because hashicorp ask that the provider should be named like the product (which is obviously cloudfoundry not cf).

Sorry to have worry you. We are working on by changes available in PR #203 which will become a major version (because of the word you don't like ) and we promise that we will following semver clearly.

I'm closing as it is a suggestion
