### ISSUE TITLE
Build is getting failed and ldap-up.sh is not there

### ISSUE THREAD

**Issue by VaishnaviGopal** [cloudfoundry-community/terraform-provider-cf#215]
error while doing make build. And when using the plugin downloaded from releases page and trying the example given examples folder, terraform plan is not working. According to Readme.md in examples, there must be some ldap-up.sh script file that should be ran for executing terraform commands on those example templates. But the ldap-up.sh file is missing

**Comment by ArthurHlt** [comment]
You're talking about using ldap. For the make build, maybe you talk about from ldap provider made by @mevansam ? the script is here: https://github.com/mevansam/terraform-provider-ldap in the provider readme talk about in fact. Example you're looking is to use this provider with another (the ldap in the previous i gave).
I'm closing it because this example is still here for history (I don't think any current committers use it)
